services:
  dev:
    image: node:20
    container_name: astro-dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4321:4321"
    command: sh -c "npm install && npm run dev"

  release:
    image: node:20
    container_name: astro-release
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"